### ISSUE TITLE
Offset value

### ISSUE THREAD

**Issue by gillboy1989** [sourceperl/pyModbusTCP#11]
When i try to read suppose MHR0 holding register - the read_holding_register function gives values from MHR1. 

It offset one value . So now can't read MHR0, rest I can read. Any help 

Thanks

**Comment by sourceperl** [comment]
I never have to deal with this but it seem that some device are not 0 based.

So for example, a read at modbus address 10000 can return the register 10001 (more at http://www.elkor.net/support/knowledgebase.php?article=14).

Peraps they are some options on your device to choose between base 0 or base 1 ? The other way is to change the read address.

**Comment by gillboy1989** [comment]
Thanks, I changed the address. simple and easy solution
