### ISSUE TITLE
Frequent _send error occurring

### ISSUE THREAD

**Issue by scottnortman** [sourceperl/pyModbusTCP#14]
I have an issue where almost every alternate read / write returns a failure.  When debug is turned on, I get a "_send error" message.

I've set the 'auto_open=True' and 'timeout=3599' but I still have this intermittent issue.  Any thoughts?

**Comment by sourceperl** [comment]
Send error typically occur when a read or write function is call on a closed TCP connection. It could be useful to watch network traffic with a tool like wireshark or tcpdump to fix this.
