### ISSUE TITLE
doc error: Function code mismatch

### ISSUE THREAD

**Issue by ford--prefect** [sourceperl/pyModbusTCP#15]
In pyModbusTCP.client there is a subtle error in line 620 [0]
Since WRITE_MULTIPLE_COILS is Modbus function code 16 (or 0x10) it should read
 `"""Modbus function WRITE_MULTIPLE_COILS (0x10)`

[0] https://github.com/sourceperl/pyModbusTCP/blob/master/pyModbusTCP/client.py#L620

**Comment by sourceperl** [comment]
Write multiple coils is function 15, write multiple **registers** is function 16.

**Comment by ford--prefect** [comment]
Oh, correct. Sorry, my bad. If function code 16 implemented in pyModbusTCP as well?

**Comment by sourceperl** [comment]
Yes, function 16 is implemented as write_multiple_registers(regs_addr, regs_value) method.

sincerely
Loïc
