### ISSUE TITLE
ModbusServer should use const.MODBUS_PORT instead of hard coded value

### ISSUE THREAD

**Issue by akobyl** [sourceperl/pyModbusTCP#16]
This is a very minor issue but I noticed the client uses const.MODBUS_PORT (defined as 502) and the server has a hard coded 502 integer in the __init__ function.  These should probably match.

https://github.com/sourceperl/pyModbusTCP/blob/9b97509e5e38270a847aa878149aa22b10c55541/pyModbusTCP/server.py#L210

**Comment by sourceperl** [comment]
It's fix on repositorie and will be included in the next release.

Thank's !
