### ISSUE TITLE
Timeout...

### ISSUE THREAD

**Issue by bonaime** [sourceperl/pyModbusTCP#2]
The new timeout parameter of #1 is not enough because it is not used in the sockets of pyModbusTCP. Therefore, if the host is down, even whith a short timeout (1 second) the open() function timeout after 30 seconds or more.

**Comment by bonaime** [comment]
It seems that it is impossible to set the timeout of socket.getaddrinfo
http://stackoverflow.com/questions/26857922/pass-timeout-to-socket-getaddrinfo

**Comment by sourceperl** [comment]
Ok thanks, sorry for the answer delay...
