### ISSUE TITLE
Client write_coils -> bit_addr out of range (for 401420)

### ISSUE THREAD

**Issue by bootsch** [sourceperl/pyModbusTCP#20]
When attempting to write (or read) coils the max address is 65535 as I found out.
I need to writ to much higher addresses. Which seems to work just once only.

What is the reason for this limit?
Is there a way to address higher values?

**Comment by sourceperl** [comment]
Modbus data address are 16 bits wide, so it's a protocol limit.

**Comment by bootsch** [comment]
Check, thank you for the clarification.
