### ISSUE TITLE
add conversion to 64 bits integer and double

### ISSUE THREAD

**Issue by FredM67** [sourceperl/pyModbusTCP#27]
[pyModbusTCP.utils.txt](https://github.com/sourceperl/pyModbusTCP/files/4542245/pyModbusTCP.utils.txt)

Hi,
I've just wrote 2 functions to add support for longlong and for double.
May I upload them?
Fred

**Comment by sourceperl** [comment]
Hi, it's now include in pyModbusTCP since 2fe2ed305205e8fca0b92f8d98fca0b838558257 for 64 bits integer and 0fd38305c455edd3a6e26f395c9da6b7bf6b5f19 for double.

Have a nice day,
Loïc
