### ISSUE TITLE
Many device

### ISSUE THREAD

**Issue by aledisi** [sourceperl/pyModbusTCP#31]
Hi,
Thank you for pyModbusTCP library. Very useful.
 I want to know if there are limitation when I want to read data simultaneously from many devices. In my case 32 ModbusTCP servers and I want to develop the client using your library.
Thank you 
Alessandro

**Comment by sourceperl** [comment]
Hi,  
At pyModbusTCP level there are no limitation. For your use case, you just have to create one modbus client for each device.
