### ISSUE TITLE
modbus RTU

### ISSUE THREAD

**Issue by dawidce** [sourceperl/pyModbusTCP#32]
Hi,

im trying to connect to device which supports modbus rtu. I have rs485 to ethernet converter. Can I use this library ?

**Comment by black-syphilis** [comment]
Hi,
Yes suppose to, you can change mode to MODBUS_RTU (check in client.py, line 235) but I never try it.

**Comment by black-syphilis** [comment]
Finally you can't. You can do it with pyModbus
