### ISSUE TITLE
server.py struct.pack problem

### ISSUE THREAD

**Issue by xuantw** [sourceperl/pyModbusTCP#35]
Hi guys,
When I use Modbustcp function and DataBank,
I found that setting a negative number will cause struct.pack exception error,

Use the following fix to avoid this problem
Add server.py Line137
tx_body += struct.pack('>H', word) is fixed as
tx_body += struct.pack('>H', word & 0xFFFF)

Is this feasible?

**Comment by sourceperl** [comment]
Hi, now (commit e8f25fb0a588e82848b861de93cc9091add42364) this is include in DataBank methods type check. Thanks.
