### ISSUE TITLE
Problems with clock_gettime

### ISSUE THREAD

**Issue by Lotiara** [sourceperl/pyModbusTCP#38]
Hi All
I have a working program in m laptop, but when I try to run it in an ubuntu, I get
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)

That happens whe I make a call to c.is_open()
Any idea ?
Thanks.

**Comment by sourceperl** [comment]
Seems to be very system specific, never see this kind of problem.

I'm closing this to clear the space of issues, feel free to reopen it if need.
