### ISSUE TITLE
Passing a list which contains integer and float value to write_multiple_registers #10

### ISSUE THREAD

**Issue by Gokila02** [sourceperl/pyModbusTCP#39]
Hi all,

I am having list of data with the data types of integer and float.
I splitted the list of data's into two lists, one list containing integers and another list containing float
when i try to passing the two lists (integers and float) into write_single_register and write_multiple_registers respectively.
integer list = [202104001,15540,1196955]
float list = [147.91,074.23,050.23,221.20,110.11,110.23,005.00,055.10,220.50]

i did not read the exact output.

For integer output:
[1]: 201326592.000000
[3]: 15535.450195
[5]: 1202688.000000

For float output:
[7]: 147.112671
[9]: 74.455002
[11]: 50.115002
[13]: 221.919998
[15]: 110.099998
[17]: 110.110001
[19]: 5.014375
[21]: 55.000000
[23]: 220.399994

Please suggest me, how to write and read the integer and float datas

**Comment by sourceperl** [comment]
You can have a look at https://pymodbustcp.readthedocs.io/en/latest/quickstart/index.html#utils-module-modbus-data-mangling
