### ISSUE TITLE
Reading %MD

### ISSUE THREAD

**Issue by alatellaCSR** [sourceperl/pyModbusTCP#42]
I'm trying to read one %MD from PLC with read_holding_register, but it returns always zero. 
Can pyModbusTCP read MD from PLC?
Thanks

**Comment by sourceperl** [comment]
If it still a need for you:

%MD0 = %MW0 and %MW1

So you can read %MW0 and %MW1 and reassembling it after.

See https://pymodbustcp.readthedocs.io/en/latest/quickstart/index.html#utils-module-modbus-data-mangling, section "read of 32 bits registers".
