### ISSUE TITLE
How to do read file operation using pyModbusTCP library?

### ISSUE THREAD

**Issue by VigneshwaranKR** [sourceperl/pyModbusTCP#49]
I'm trying to do read a file from device.But i couldn't able to find the FC20 to read the file.Is pyModbusTCP library support Read File.If Yes,how to do it? @sourceperl

**Comment by sourceperl** [comment]
FC20 is not implemented.

https://pymodbustcp.readthedocs.io/en/latest/quickstart/index.html#modbusclient-available-modbus-requests-functions
