### ISSUE TITLE
TCP connection open/close

### ISSUE THREAD

**Issue by suibaf** [sourceperl/pyModbusTCP#6]
Hi,
second your opinion, what is the best solution:
1) connection always open
2) connection open/close for each request.

best regards

**Comment by sourceperl** [comment]
Hi,

If your information exchange is always on (read/write every second or minute) it's probably  better to maintain TCP connection open. With some devices it can be difficult to do that. Especialy if it's resource level are realy low and TCP socket number are limited.

So the better way, is to do some test with the target device and see what happen.

Loïc
