### ISSUE TITLE
cannot use custom handler or/and databank when create server object

### ISSUE THREAD

**Issue by rkrikbaev** [sourceperl/pyModbusTCP#66]
https://github.com/sourceperl/pyModbusTCP/blob/cd22c569bf22080405835945bf813c7a75d95262/pyModbusTCP/server.py#L724

These assignments (self.handler=None and self.databank=None) make it impossible to use a custom handler and/or databank further

**Comment by sourceperl** [comment]
I'm not sure to understand what is wrong here.

I juste use [server_virtual_data.py](https://github.com/sourceperl/pyModbusTCP/tree/master/examples/server_virtual_data.py) which use a custom databank without any problem.

So I'm closing this topic, feel free to reopen it with more details if it's still a problem for you.
