### ISSUE TITLE
0.2.1 Syntax Error

### ISSUE THREAD

**Issue by SimoVeneri** [sourceperl/pyModbusTCP#76]
0.2.1 has introduced this error:

File "/usr/local/lib/python3.5/dist-packages/pyModbusTCP/client.py", line 30
    conformity_level int = 0
                       ^
SyntaxError: invalid syntax

**Comment by sourceperl** [comment]
It looks like you are trying to run pyModbusTCP on an unsupported version of Python. Python 3.5 reached end of life in 2020, pyModbusTCP is currently testing on Python 3.7 to 3.11.
