### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by faizwal** [sourceperl/pyModbusTCP#77]
![422903155_411789414749545_6772750980438941309_n](https://github.com/sourceperl/pyModbusTCP/assets/156782990/99264ed4-c474-4a62-baa5-e9066da2531b)

**Comment by sourceperl** [comment]
This is not a pyModbusTCP issue but it is a new behavior of the Raspberry Pi OS. Take a look at the Raspberry documentation: https://www.raspberrypi.com/documentation/computers/os.html#about-python-virtual-environments to learn how to deal with this.
