### ISSUE TITLE
Having Issues using Write Operation

### ISSUE THREAD

**Issue by meetvigneshbalaji** [sourceperl/pyModbusTCP#80]
Hi, 

I am having issues using Write Operation using this driver. I want to send 32 bit value to an register. I understand the standard Modbus standard is 16 bit. So I have modified the "write_single_register" class by enabling it send 32 bits. I am using Wireshark to compare the data being sent from a different software in Windows and comparing the data being sent from my Rasperry pi platform and they are exactly the same. Though the unit does not throw an error, the write operation does not work. I verify it by checking another register if the operation had been successful and through that I know the operation is an failure. 
I am wondering if anyone could help me understand what is going on. 

OS: Debian
Platform: Rasperry pi 4
Version: PymodbusTCP-0.2.1 

Source Code: 

from myModbusTCP.client import ModbusClient
import time

c = ModbusClient(host="xxx.xxx.xxx.xxx", unit_id=1, auto_open=True, auto_close=True, debug=True)

r = c.write_single_register(0xfxxx, 1425xxxxxxxx) ##write 32 bit value to this register
time.sleep(1)

r = c.write_factory_single_register(0xfxxx,0) ## I created this class. This is basically an copy of original write single register where we can write only 16 bit value. This is being done to verify the previous operation is successful failing which I cannot write to this register. 

Now, I have it working from windows from an different software. I have to accomplish this in python. So I compared the Wireshark data bit to bit and they are exactly the same. I do not know why the Python driver is not writing to the register as expected. 

Any inputs would be welcome. 

Thank you

**Comment by sourceperl** [comment]
Hi,

For 32-bit writing, you cannot use the modbus function 6 (write_single_register) because it can only write a single 16-bit register.

Could you try this code with your host and register address and show me the output ?

```python
from pyModbusTCP.client import ModbusClient
from pyModbusTCP.utils import long_list_to_word, word_list_to_long


class MyModbusClient(ModbusClient):
    def read_long(self, address: int, number: int = 1, big_endian: bool = True) -> list | None:
        b16_l = self.read_holding_registers(address, number * 2)
        if not b16_l:
            return
        return word_list_to_long(b16_l, big_endian=big_endian)

    def write_long(self, address: int, long_list: list, big_endian: bool = True) -> bool:
        b16_l = long_list_to_word(long_list, big_endian=big_endian)
        return self.write_multiple_registers(address, b16_l)


if __name__ == '__main__':
    # init modbus client
    c = MyModbusClient(host='localhost', port=502)

    # turn on debug
    c.debug = True

    # write a long at address 0
    address = 0
    w_value = 0xc0ffee00
    print(f'write 0x{w_value:X} at @{address}')
    c.write_long(address, long_list=[w_value])

    # read a long at address 0
    print(f'\nread at @{address}')
    long_l = c.read_long(address, number=1)
    if long_l:
        print(f'return 0x{long_l[0]:X}')

    c.close()
```

You should have something like this:
```
write 0xC0FFEE00 at @0
Tx
[A2 CC 00 00 00 0B 01] 10 00 00 00 02 04 C0 FF EE 00
Rx
[A2 CC 00 00 00 06 01] 10 00 00 00 02

read at @0
Tx
[E2 BC 00 00 00 06 01] 03 00 00 00 02
Rx
[E2 BC 00 00 00 07 01] 03 04 C0 FF EE 00
return 0xC0FFEE00
```
