### ISSUE TITLE
discrete inputs get and set are mistakenly configured for coils

### ISSUE THREAD

**Issue by OTnetproj** [sourceperl/pyModbusTCP#84]
`
    def get_discrete_inputs(self, address, number=1, srv_info=None):
        """Read data on server discrete inputs space

        :param address: start address
        :type address: int
        :param number: number of bits (optional)
        :type number: int
        :param srv_info: some server info (must be set by server only)
        :type srv_info: ModbusServerInfo
        :returns: list of bool or None if error
        :rtype: list or None
        """
        # secure extract of data from list used by server thread
        with self._d_inputs_lock:
            if (address >= 0) and (address + number <= len(self._coils)):
                return self._d_inputs[address: number + address]
            else:
                return None

    def set_discrete_inputs(self, address, bit_list):
        """Write data to server discrete inputs space

        :param address: start address
        :type address: int
        :param bit_list: a list of bool to write
        :type bit_list: list
        :returns: True if success or None if error
        :rtype: bool or None
        :raises ValueError: if bit_list members cannot be converted to bool
        """
        # ensure bit_list values are bool
        bit_list = [bool(b) for b in bit_list]
        # ensure atomic update of internal data
        with self._d_inputs_lock:
            if (address >= 0) and (address + len(bit_list) <= len(self._coils)):
                for offset, b_value in enumerate(bit_list):
                    self._d_inputs[address + offset] = b_value
            else:
                return None
        return True
`

get and set for discrete inputs checks the length of DataBank's self._coils attribute where it should go by self._d_inputs length or self._d_inputs_size

This leads to a bug where server and client cannot read/set the Server's discrete inputs array beyond self._coils_size

**Comment by sourceperl** [comment]
Hi, thanks for this report.

Fix in commit [ef2c457](https://github.com/sourceperl/pyModbusTCP/commit/ef2c457cc0cadc1f8c987cbd7be4c2a2e3c33839)
