### ISSUE TITLE
AttributeError: 'module' object has no attribute 'inet_pton'

### ISSUE THREAD

**Issue by rolliracker** [sourceperl/pyModbusTCP#9]
Hi,
First, thank you very much for the code!
On Windows 7, using Python 2.7 (32 bit), when I tried 
`c = ModbusClient(host="127.0.0.1", auto_open=True, auto_close=True)`
I got an exception saying:
`Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    c = ModbusClient(host="127.0.0.1", auto_open=True, auto_close=True)
  File "C:\WinPython-32bit-2.7.10.3\python-2.7.10\lib\site-packages\pyModbusTCP\client.py", line 61, in __init__
    if not self.host(host):
  File "C:\WinPython-32bit-2.7.10.3\python-2.7.10\lib\site-packages\pyModbusTCP\client.py", line 126, in host
    socket.inet_pton(socket.AF_INET, hostname)
AttributeError: 'module' object has no attribute 'inet_pton'
`
I solved this by running `pip install win-inet-pton` and adding `import win_inet_pton` in my code, as explained here: [https://github.com/mitsuhiko/python-geoip/issues/4](url) 

Roland

**Comment by dbe-hms** [comment]
Thanks I was running into this same problem!

**Comment by muthunsr** [comment]
Thanks i had same issue. Now the code is running successfully!!

**Comment by shachashou** [comment]
Thanks , it  helps me a lot

**Comment by Redcof** [comment]
Thanks.

**Comment by sourceperl** [comment]
I add notice to README to warn windows user about this.
